repos:
  # 基本的なファイル整合性チェック
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending

  # ShellCheck - シェルスクリプト解析
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        files: \.(sh|bash|zsh)$

  # vint - Vimスクリプト解析
  - repo: https://github.com/Vimjas/vint
    rev: v0.4a3
    hooks:
      - id: vint
        files: \.(vim|vimrc)$
