---
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  indentation:
    indent-sequences: whatever
  line-length:
    max: 120
  truthy:
    check-keys: false
